name: packaging
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - v4.x
    tags:
      - v*.*.*
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - "ruby"
          - "x64-mingw32"
          - "x64-mingw-ucrt"
          - "x86_64-darwin"
          - "arm64-darwin"
          - "x86_64-linux-gnu"
          - "x86_64-linux-musl"
          - "aarch64-linux-gnu"
          - "aarch64-linux-musl"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm Gemfile.lock
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler: latest
          bundler-cache: true
      - run: "bundle exec rake gem:${{matrix.platform}}"
      - uses: actions/upload-artifact@v4
        with:
          name: gem-${{matrix.platform}}
          path: pkg
          retention-days: 1

  vanilla-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v4
        with:
          name: gem-ruby
          path: pkg
      - run: "gem install pkg/tailwindcss-ruby-*.gem"
      - run: "tailwindcss 2>&1 | fgrep 'ERROR: Cannot find the tailwindcss executable'"

  linux-x86_64-gnu-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v4
        with:
          name: gem-x86_64-linux-gnu
          path: pkg
      - run: "gem install pkg/tailwindcss-ruby-*.gem"
      - run: "tailwindcss --help"

  linux-x86_64-musl-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: gem-x86_64-linux-musl
          path: pkg
      - run: |
          docker run --rm -v $PWD:/tailwindcss-ruby -w /tailwindcss-ruby \
            ruby:3.2-alpine \
            sh -c "
              apk add build-base
              gem install pkg/tailwindcss-ruby-*.gem
              tailwindcss --help
            "

  linux-aarch64-gnu-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v4
        with:
          name: gem-aarch64-linux-gnu
          path: pkg
      - run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm -v $PWD:/tailwindcss-ruby -w /tailwindcss-ruby \
            --platform=linux/arm64/v8 ruby:3.2 \
            sh -c "
              gem install pkg/tailwindcss-ruby-*.gem
              tailwindcss --help
            "

  linux-aarch64-musl-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: gem-aarch64-linux-musl
          path: pkg
      - run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm -v $PWD:/tailwindcss-ruby -w /tailwindcss-ruby \
            --platform=linux/arm64/v8 ruby:3.2-alpine \
            sh -c "
              apk add build-base
              gem install pkg/tailwindcss-ruby-*.gem
              tailwindcss --help
            "

  darwin-x86_64-install:
    needs: ["package"]
    runs-on: macos-13
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v4
        with:
          name: gem-x86_64-darwin
          path: pkg
      - run: "gem install pkg/tailwindcss-ruby-*.gem"
      - run: "tailwindcss --help"

  darwin-arm64-install:
    needs: ["package"]
    runs-on: macos-14
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v4
        with:
          name: gem-arm64-darwin
          path: pkg
      - run: "gem install pkg/tailwindcss-ruby-*.gem"
      - run: "tailwindcss --help"

  windows-install:
    needs: ["package"]
    runs-on: windows-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - uses: actions/download-artifact@v4
        with:
          name: gem-x64-mingw32
          path: pkg
      - run: "gem install pkg/tailwindcss-ruby-*.gem"
      - run: "tailwindcss --help"

  windows-ucrt-install:
    needs: ["package"]
    runs-on: windows-2022
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v4
        with:
          name: gem-x64-mingw-ucrt
          path: pkg
      - run: "gem install pkg/tailwindcss-ruby-*.gem"
      - run: "tailwindcss --help"
